# Generated by Django 3.2.5 on 2021-08-30 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='priority',
            field=models.CharField(choices=[('important', 'important'), ('less important', 'less import'), ('not important', 'not important')], max_length=50),
        ),
    ]
